### PR TITLE
Multiple ogre

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Follow-up on https://github.com/conda-forge/libignition-rendering4-feedstock/pull/8

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
I think the CDN still needs to propagate .. the libignition-rendering build for ogre1.10 is not yet found

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please restart CI

**Comment by Tobias-Fischer** [comment]
Win fails because https://github.com/ignitionrobotics/ign-gui/blob/ign-gui4/tools/check_test_ran.py tries to "grep" which is not available on Windows.

**Comment by traversaro** [comment]
Strange, I thought I had added  `-E check_`  to the ctest invocation on Windows. Given that this problem is just a Python script that was not properly updated and not an actual test failing, I think we can just added a `-E check_`.

**Comment by traversaro** [comment]
> 
> 
> Win fails because https://github.com/ignitionrobotics/ign-gui/blob/ign-gui4/tools/check_test_ran.py tries to "grep" which is not available on Windows.

Workarounded in https://github.com/conda-forge/libignition-gui-feedstock/pull/1/commits/a951b60e972e6880e0fae84a6d1b9715d069cbe2, opened upstream issue in https://github.com/ignitionrobotics/ign-gui/issues/198 (probably it is just sufficient to apply patch https://github.com/ignitionrobotics/ign-math/commit/69d881d51c78929f096791a31f23b87f6032ee88#diff-2d6a060081b4c12efdbe4f12e846ead21821236e834f41885a04e41e884687c2).

**Review by traversaro — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
Fix #2. Thanks @traversaro. This is ready to be merged.

**Comment by traversaro** [comment]
Thanks @Tobias-Fischer !

**Comment by traversaro** [comment]
By the way, this PR also permits to upload Windows binaries, as for some reason https://github.com/conda-forge/libignition-gui-feedstock/issues/2 was not occuring in staged-recipes, but post merge made the Windows build fail.

**Pull request merged**
